- hosts: localhost
  vars:
   host: "192.168.122.40"
   username: "admin"
   password: ""
   vdom: "global"
  tasks:
  - name: backup system config
    fortiosconfig:
     config: "system config restore"
     action: "restore"
     host:  "{{ host }}"
     username: "{{ username }}"
     password: "{{ password }}"
     vdom:  "{{ vdom }}"
     config_parameters:
      filename: "backup_config_001"
